"""KPI governance automation tests (Priority 2 of the final local
completion pass).

These validate *alignment* — every governed KPI actually exists in the
public output(s) it claims, its observed values respect the declared
range, its metadata marks it public-safe with no forbidden-name collision,
and docs/kpi_catalog.md still mentions it. This is metadata/presence/range
governance, not a proof that a formula can never silently diverge from its
documentation — the formulas themselves remain centralized in
shared/metrics.py, shared/profitability.py, shared/public_output_builder.py,
and shared/recommendations.py.
"""

from __future__ import annotations

from pathlib import Path

import pandas as pd
import pytest

from shared.kpi_registry import (
    FORBIDDEN_COLUMN_NAMES,
    REGISTRY,
    all_kpi_names,
    find_kpi,
    regenerate_kpi_catalog_table,
    render_registry_table_markdown,
    validate_documentation_references,
    validate_kpi_presence,
    validate_kpi_ranges,
    validate_public_safety,
)

PUBLIC_DIR = Path(__file__).resolve().parents[1] / "data" / "public"


def _load_real_outputs() -> dict[str, pd.DataFrame]:
    outputs = {}
    for path in PUBLIC_DIR.glob("*.csv"):
        outputs[path.stem] = pd.read_csv(path)
    return outputs


def test_registry_is_non_empty_and_names_are_unique():
    assert len(REGISTRY) >= 10
    names = all_kpi_names()
    assert len(names) == len(set(names))


def test_find_kpi_returns_none_for_unknown_name():
    assert find_kpi("Definitely Not A Real KPI") is None


def test_find_kpi_returns_the_definition():
    kpi = find_kpi("Sales Index")
    assert kpi is not None
    assert kpi.output_column == "sales_index"


def test_every_governed_kpi_has_formatting_metadata():
    for kpi in REGISTRY:
        assert kpi.format and kpi.format.strip(), f"{kpi.kpi_name} is missing format metadata"


def test_every_governed_kpi_is_marked_public_safe():
    report = validate_public_safety()
    assert report["governance_ok"].all(), report[~report["governance_ok"]]


def test_no_governed_kpi_collides_with_forbidden_column_names():
    for kpi in REGISTRY:
        assert kpi.output_column not in FORBIDDEN_COLUMN_NAMES


def test_every_governed_kpi_is_documented_in_kpi_catalog():
    report = validate_documentation_references()
    assert report["documented"].all(), report[~report["documented"]]


# ---------------------------------------------------------------------------
# Presence + range checks against the real, currently-generated public
# outputs (regenerated by the pipeline in data/public/).
# ---------------------------------------------------------------------------


@pytest.fixture(scope="module")
def real_outputs() -> dict[str, pd.DataFrame]:
    outputs = _load_real_outputs()
    if not outputs:
        pytest.skip("data/public/*.csv not present — run the pipeline first")
    return outputs


def test_every_governed_kpi_column_exists_in_at_least_one_real_output(real_outputs):
    report = validate_kpi_presence(real_outputs)
    missing = report[~report["present"]]
    assert missing.empty, f"KPIs with no matching column in any real public output: {missing['kpi_name'].tolist()}"


def test_no_governed_kpi_output_is_missing_from_an_output_that_claims_it(real_outputs):
    # A KPI claiming to appear in an output that DOES exist on disk must
    # genuinely carry that column -- this catches a KPI/output going stale
    # after a future refactor (Requirement 29: "no stale KPI name remains").
    report = validate_kpi_presence(real_outputs)
    stale = report[report["missing_from"].map(bool)]
    assert stale.empty, f"KPIs claiming an output that no longer carries the column: {stale.to_dict('records')}"


def test_numeric_kpi_values_fall_within_expected_range_on_real_data(real_outputs):
    report = validate_kpi_ranges(real_outputs)
    assert not report.empty
    out_of_range = report[~report["in_range"]]
    assert out_of_range.empty, f"KPI values outside expected range: {out_of_range.to_dict('records')}"


def test_no_undocumented_core_kpi_column_silently_introduced(real_outputs):
    # Every registry output_column that appears anywhere in the real data
    # must be exactly the column name declared -- guards against a rename
    # (e.g. sales_index -> salesIndex) going unnoticed by the registry.
    for kpi in REGISTRY:
        for output_name in kpi.source_outputs:
            if output_name not in real_outputs:
                continue
            columns = set(real_outputs[output_name].columns)
            # A close-but-not-exact match (case/underscore drift) would be
            # invisible to a plain "in columns" check, so also assert no
            # near-miss variant exists unless the exact name is present.
            if kpi.output_column not in columns:
                near_misses = [c for c in columns if c.lower().replace("_", "") == kpi.output_column.lower().replace("_", "")]
                assert not near_misses, (
                    f"{kpi.kpi_name}: expected column '{kpi.output_column}' not found in {output_name}, "
                    f"but a near-miss variant exists: {near_misses} -- registry is stale"
                )


# ---------------------------------------------------------------------------
# Documentation generation
# ---------------------------------------------------------------------------


def test_render_registry_table_markdown_includes_every_kpi():
    table = render_registry_table_markdown()
    for kpi in REGISTRY:
        assert kpi.kpi_name in table
        assert kpi.output_column in table


def test_regenerate_kpi_catalog_table_is_idempotent(tmp_path, monkeypatch):
    # Regenerating twice in a row must produce byte-identical output.
    content_a = regenerate_kpi_catalog_table(write=False)
    content_b = regenerate_kpi_catalog_table(write=False)
    assert content_a == content_b


def test_kpi_catalog_markers_are_present_in_the_real_file():
    from shared.kpi_registry import KPI_CATALOG_PATH, REGISTRY_TABLE_BEGIN, REGISTRY_TABLE_END

    text = KPI_CATALOG_PATH.read_text(encoding="utf-8")
    assert REGISTRY_TABLE_BEGIN in text
    assert REGISTRY_TABLE_END in text


def test_kpi_catalog_file_on_disk_matches_current_registry():
    # The committed docs/kpi_catalog.md table must already reflect the
    # current registry -- if this fails, someone changed the registry
    # without regenerating the docs.
    from shared.kpi_registry import KPI_CATALOG_PATH

    on_disk = KPI_CATALOG_PATH.read_text(encoding="utf-8")
    assert render_registry_table_markdown() in on_disk
